const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
for (const file of ['js/teacher.js', 'js/curriculum-release.js']) {
    const source = fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
    const extract = (start, end) => source.slice(source.indexOf(start), source.indexOf(end, source.indexOf(start)));
    assert.ok(source.includes('Assigned Students - ${draft._prevStep'), file);
    assert.ok(source.includes('hasChanged = hasChanged || selected !== draft._initialSnapshot.assignedStudents'), file);
    assert.ok(!source.includes("expandedAssigned.add('all')"), 'Selecting the current roster must not assign future students');
    const draft = { _targetId: 'quiz', _subjectId: 'prog1', _section: 'Rizal', _activeStep: 'grading', assignedStudents: { quiz: ['all', '*'] }, ids: ['quiz', 'task'] };
    const students = [{ id: 'one', name: 'One' }, { id: 'two', name: 'Two' }];
    const window = { draft, getUnifiedScheduleMeta: () => ({ draftStateKey: 'draft', pendingKey: 'ids' }), getStudentsForSection: () => students };
    let overlay = { dataset: { _category: 'assessments', _activeStep: 'students', _editType: 'grading' } };
    const document = { getElementById: id => id === 'teacher-topic-schedule-overlay' ? overlay : null };
    const context = vm.createContext({ window, document, draft, sectionStudents: students, effIdStr: 'quiz', currentTopicState: {}, console });
    vm.runInContext(extract('        const storedAssigned =', '        const currentAssignedList ='), context);
    assert.deepEqual(Array.from(draft.assignedStudents.quiz), ['one', 'two']);
    vm.runInContext(extract('    window.toggleTeacherScheduleStudent =', '    window.toggleTeacherScheduleSelectAllStudents ='), context);
    window.toggleTeacherScheduleStudent('assessments', 'quiz', 'two');
    assert.deepEqual(Array.from(draft.assignedStudents.quiz), ['one']);
    assert.deepEqual(Array.from(draft.assignedStudents.task), ['one'], 'Apply All survives the roster step without its checkbox');
    let opened;
    window.openTeacherUnifiedScheduleModal = (...args) => { opened = args; };
    vm.runInContext(extract('    window.goToTeacherScheduleStep =', '    window.cacheActiveAssessmentGradingSettings ='), context);
    window.goToTeacherScheduleStep('assessments', 'quiz', 'students');
    assert.equal(draft._prevStep, 'grading');
    vm.runInContext(extract('    window.closeTeacherTopicScheduleModal =', '    window.saveTeacherUnifiedSchedule ='), context);
    window.closeTeacherTopicScheduleModal(true);
    assert.equal(opened[3], 'grading', 'Browser/phone Back returns to Details');
    draft._prevStep = 'schedule';
    window.closeTeacherTopicScheduleModal(true);
    assert.equal(opened[3], 'schedule', 'Browser/phone Back returns to Schedule');
    const saveButton = { disabled: true, attrs: {}, classList: { add() {}, remove() {} }, setAttribute(name, value) { this.attrs[name] = value; }, removeAttribute(name) { delete this.attrs[name]; } };
    overlay.dataset._editType = 'schedule';
    overlay.dataset._activeStep = 'schedule';
    overlay.dataset._isQuiz = 'true';
    draft._initialSnapshot = { isReleaseNow: true, isNoDeadline: true, dateVal: '', timeVal: '', endDateVal: '', endTimeVal: '', assignedStudents: JSON.stringify(['one', 'two']) };
    window.getUnifiedScheduleMeta = () => ({ draftStateKey: 'draft', pendingKey: 'ids', scheduleKey: 'schedules', endScheduleKey: 'endSchedules' });
    draft.schedules = { quiz: 'now' };
    draft.assessmentMaxScores = { quiz: 100, task: 100 };
    window.getTeacherSubjectAssessments = () => [{ id: 'quiz', type: 'Quiz' }, { id: 'task', type: 'Task' }];
    document.getElementById = id => id === 'teacher-topic-schedule-overlay' ? overlay : id === 'teacher-save-schedule-btn' ? saveButton : null;
    context.localStorage = { getItem: () => '' };
    vm.runInContext(extract('    window.validateTeacherScheduleInputs =', '    window.updateScheduleHelperSummary ='), context);
    assert.equal(window.validateTeacherScheduleInputs('assessments'), true, 'Schedule uses the same default attempts as Details');
    assert.equal(saveButton.disabled, false, 'Student-only Schedule edits enable Save');
    draft.assignedStudents.quiz = ['two', 'one'];
    window.validateTeacherScheduleInputs('assessments');
    assert.ok(saveButton.disabled || saveButton.attrs['aria-disabled'] === 'true', 'Restoring the roster clears the dirty state regardless of order');
    draft.assessmentMaxAttempts = { quiz: 0 };
    assert.equal(window.validateTeacherScheduleInputs('assessments'), false, 'Invalid attempts are still rejected');
    const saveAssignments = extract('            const copyAssignedList =', '            if (category === \'assessments\') {');
    const saveContext = vm.createContext({ draft, saved: { assignedStudents: { quiz: ['all'] } }, idStr: 'quiz', effFallbackAssigned: ['two'], isApplyAll: true, defaultChosenStudentIds: ['one', 'two'], secStudentMap: new Map([['one', students[0]], ['two', students[1]]]), config: { assignedStudents: {} } });
    draft.assignedStudents.quiz = ['one'];
    vm.runInContext(saveAssignments, saveContext);
    assert.ok(saveContext.config.assignedStudents.quiz.includes('one'));
    assert.ok(!saveContext.config.assignedStudents.quiz.includes('two'));
    assert.ok(!saveContext.config.assignedStudents.quiz.includes('all'));
    draft.assignedStudents.quiz = [];
    vm.runInContext(`(() => { ${saveAssignments} })()`, saveContext);
    assert.deepEqual(Array.from(saveContext.config.assignedStudents.quiz), [], 'An explicitly empty roster does not fall back to all students');
}
console.log('PASS: roster aliases normalize, student-only changes enable Save, assignments survive step navigation and Apply All');
